// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new containers API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for containers API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	CreateContainer(params *CreateContainerParams) (*CreateContainerCreated, error)

	ListContainers(params *ListContainersParams) (*ListContainersOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CreateContainer Create a container
*/
func (a *Client) CreateContainer(params *CreateContainerParams) (*CreateContainerCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateContainerParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "create_container",
		Method:             "POST",
		PathPattern:        "/container",
		ProducesMediaTypes: []string{"application/github.com.bensallen.rbd.v1+json"},
		ConsumesMediaTypes: []string{"application/github.com.bensallen.rbd.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CreateContainerReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateContainerCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CreateContainerDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  ListContainers Get a list of containers
*/
func (a *Client) ListContainers(params *ListContainersParams) (*ListContainersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListContainersParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "list_containers",
		Method:             "GET",
		PathPattern:        "/container",
		ProducesMediaTypes: []string{"application/github.com.bensallen.rbd.v1+json"},
		ConsumesMediaTypes: []string{"application/github.com.bensallen.rbd.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListContainersReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListContainersOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListContainersDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
