// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Rados Block Device Boot
//
//  Manage RBD devices, mounts, and containers
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/github.com.bensallen.rbd.v1+json
//
//  Produces:
//    - application/github.com.bensallen.rbd.v1+json
//
// swagger:meta
package restapi
